### ISSUE TITLE
Navbar: Sometimes 'Title Case' and sometimes 'Regular case'

### ISSUE THREAD

**Issue by HenrikBengtsson** [satRdays/quarto-satrdays-template#4]
FYI, some submenus use 'Title Case' and others 'Regular case', e.g. 'Call for Submissions', 'Key dates', and 'Organizing committee'.

**Comment by benubah** [comment]
Thanks! Will add a style that auto-fixes this automatically

**Comment by benubah** [comment]
Fixed in https://github.com/satRdays/quarto-satrdays-template/commit/66f1ba46a611700e6e8bcf34d788b24ce2c969cb
